In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('advertising.csv')

In [3]:
df.head(3)

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   

                        Ad Topic Line         City  Male     Country  \
0  Cloned 5thgeneration orchestration  Wrightburgh     0     Tunisia   
1  Monitored national standardization    West Jodi     1       Nauru   
2    Organic bottom-line service-desk     Davidton     0  San Marino   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0

In [4]:
df.shape

(1000, 10)

In [6]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [7]:
df.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Ad Topic Line', 'City', 'Male', 'Country',
       'Timestamp', 'Clicked on Ad'],
      dtype='object')

In [8]:
df.isnull().sum()

Daily Time Spent on Site    0
Age                         0
Area Income                 0
Daily Internet Usage        0
Ad Topic Line               0
City                        0
Male                        0
Country                     0
Timestamp                   0
Clicked on Ad               0
dtype: int64

In [9]:
df.describe()

Daily Time Spent on Site          Age   Area Income  \
count               1000.000000  1000.000000   1000.000000   
mean                  65.000200    36.009000  55000.000080   
std                   15.853615     8.785562  13414.634022   
min                   32.600000    19.000000  13996.500000   
25%                   51.360000    29.000000  47031.802500   
50%                   68.215000    35.000000  57012.300000   
75%                   78.547500    42.000000  65470.635000   
max                   91.430000    61.000000  79484.800000   

       Daily Internet Usage         Male  Clicked on Ad  
count           1000.000000  1000.000000     1000.00000  
mean             180.000100     0.481000        0.50000  
std               43.902339     0.499889        0.50025  
min              104.780000     0.000000        0.00000  
25%              138.830000     0.000000        0.00000  
50%              183.130000     0.000000        0.50000  
75%              218.792500     1.000000        1.00000  
max              269.960000     1.000000        1.00000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64  
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object 
 5   City                      1000 non-null   object 
 6   Male                      1000 non-null   int64  
 7   Country                   1000 non-null   object 
 8   Timestamp                 1000 non-null   object 
 9   Clicked on Ad             1000 non-null   int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [12]:
x=df.iloc[:,0:7]
x=x.drop(['Ad Topic Line','City'],axis=1)

In [14]:
y = df.iloc[:,9]

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [18]:
y_pred = model.predict(x_test)

In [19]:
y_pred

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1], d

In [20]:
y_pred_proba = model.predict_proba(x_test)

In [21]:
y_pred_proba

array([[9.58489045e-01, 4.15109549e-02],
       [6.49077827e-01, 3.50922173e-01],
       [9.50716072e-01, 4.92839284e-02],
       [7.98392695e-02, 9.20160731e-01],
       [9.37582601e-01, 6.24173990e-02],
       [2.91945159e-03, 9.97080548e-01],
       [2.09893325e-03, 9.97901067e-01],
       [1.62211244e-01, 8.37788756e-01],
       [9.36918373e-01, 6.30816272e-02],
       [9.52242427e-01, 4.77575731e-02],
       [9.70338076e-01, 2.96619243e-02],
       [9.41305538e-01, 5.86944623e-02],
       [2.73616261e-02, 9.72638374e-01],
       [9.34440333e-01, 6.55596672e-02],
       [9.80110232e-01, 1.98897677e-02],
       [9.00130720e-01, 9.98692804e-02],
       [7.09273297e-03, 9.92907267e-01],
       [8.46627240e-01, 1.53372760e-01],
       [1.19193056e-01, 8.80806944e-01],
       [9.52215272e-01, 4.77847275e-02],
       [9.76553895e-01, 2.34461046e-02],
       [5.88712765e-01, 4.11287235e-01],
       [8.93902717e-01, 1.06097283e-01],
       [1.56374232e-01, 8.43625768e-01],
       [2.613060

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [25]:
accuracy_score(y_test,y_pred)

0.9166666666666666

In [26]:
confusion_matrix(y_test,y_pred)

array([[155,   9],
       [ 16, 120]], dtype=int64)

In [27]:
model.score(x_train,y_train)

0.89

In [29]:
model.score(x_test, y_test)

0.9166666666666666